theme: jekyll-theme-tactile
title: Kalle Kytölä
description: not my webpage

# Site Author
author:
  name             : "Kalle Kytölä"
  avatar           : "Dyck_tilings_CIDTf-1.png"
  bio              : 
  location         : 
  employer         :
  pubmed           : 
  googlescholar    : "http://yourfullgooglescholarurl.com"
